### ISSUE TITLE
Management API Commands

### ISSUE THREAD

**Issue by foogunlana** [sir-dunxalot/cypress-nextjs-auth0#15]
Thanks for the good work here!

I noticed you recommend in the README.md to use an existing user. Is this a recommended best practice? Or is it because of the added difficulty of creating a user? For instance, I believe it's a good idea to create new users often instead of relying on existing ones. I've currently implemented the following pattern and was wondering if you think it would be useful to put in this package? (it could use a bit of work to make it useful for anyone but myself though)

```js
const getAuth0MgmtToken = (cy) => {
  cy.log('Fetching management access token...')
  return cy
    .request({
      method: 'POST',
      url: Cypress.env('auth0TokenURL'),
      body: {
        grant_type: 'client_credentials',
        client_id: Cypress.env('auth0MgmtClientId'),
        client_secret: Cypress.env('auth0MgmtClientSecret'),
        audience: Cypress.env('auth0Audience'),
        scope: Cypress.env('auth0MgmtScope')
      }
    })
    .its('body')
    .its('access_token')
}

Cypress.Commands.add('signup', (user) => {
  cy.log(`Creating user ${user.email}...`)
  getAuth0MgmtToken(cy).then((token) => {
    cy.request({
      method: 'POST',
      url: `${Cypress.env('auth0Audience')}users`,
      body: { ...user, connection: 'Username-Password-Authentication' },
      headers: {
        Authorization: `Bearer ${token}`
      }
    })
      .then(() => {
        cy.log(`Successfully created user ${user.email}`)
      })
  })
})

Cypress.Commands.add('cleanUsers', () => {
  cy.log('Cleaning users...')
  getAuth0MgmtToken(cy).then((token) => {
    const params = {
      search_engine: 'v3',
      q: 'email:*@e2e-stears.com',
      per_page: 10,
      page: 0
    }
    const url = `${Cypress.env('auth0Audience')}users?${new URLSearchParams(
      params
    ).toString()}`
    cy.request({
      method: 'GET',
      url,
      headers: {
        Authorization: `Bearer ${token}`
      }
    }).then((resp) => {
      for (const user of resp.body) {
        if (user.email.indexOf('e2e-stears.com') === -1) {
          // sanity check
          throw Error(`Not an E2E user ${user.email}`)
        } else {
          cy.request({
            method: 'DELETE',
            url: `${Cypress.env('auth0Audience')}users/${user.user_id}`,
            headers: {
              Authorization: `Bearer ${token}`
            }
          })
        }
      }
    })
  })
})
```

As cypress recommends, I focus on cleaning up only in `before`, so the e2e environment might have left over users after a test, but they will always be deleted on the next test. Obviously creating a specific email pattern to search for won't work for every user, but perhaps there's a more generic way to flag the e2e users

```
  before(() => {
    cy.cleanUsers()
    cy.cleanWhitelist()
  })
```

You can ignore `cy.cleanWhitelist` as that is a hubspot API integration

**Comment by sir-dunxalot** [comment]
Hi @foogunlana. Thank you for the time put into this description and accompanying examples. In theory, having the ability to create a user is valuable if it allows the sign up flow to be tested. However, if you're creating a user via an HTTP request rather than your sign up flow, what is the benefit vs just signing in to an existing user? The main situation I imagine this is valuable is if you're editing metadata on your Auth0 user and want to reset the user's state before a test. Whether that is common/valuable enough to warrant making this library more complex is unclear.

As for implementing this feature, I'm weary of anything that deletes users. For example, what if the developer accidentally uses their production tenant instead of the development tenant in testing? The test user's ID could be cached locally for the user deletion.

What do you think?

**Comment by foogunlana** [comment]
On your second point. I agree, I'm also weary of allowing the installer to unintentionally delete users. 
As for being able to add create new users instead of adding them via the sign up flow - I agree with your point. It's likely not enough value add to justify the added complexity of maintaining it. 👍  thanks for the answers!
